### ISSUE TITLE
Repo needs an FSF approved software license

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/QTLReaper#2]
Who are the authors of this software and what is the distribution license? The original project is listed
at https://sourceforge.net/projects/qtlreaper/ and claims a GPLv2.

Also we should credit J. Wang and Kmanly in the README for their work. Any other authors?

Lei, can you add the GPL2 license? Use more descriptive git commit messages, please.

**Comment by ghost** [comment]
Added License and Author

https://github.com/genenetwork/QTLReaper/blob/master/README.md

**Comment by pjotrp** [comment]
Thanks!
